/**
 * GENERATED by tools/recipe-emit-unocss.ts from tools/recipe-contract-definitions.ts ("button")
 * Do not edit by hand — edit the definition and re-run the emitter.
 */

import { cva, type VariantProps } from "class-variance-authority"

export const buttonVariants = cva("solidiom-btn", {
  variants: {
    variant: {
      default: "solidiom-btn--default",
      destructive: "solidiom-btn--destructive",
      outline: "solidiom-btn--outline",
      secondary: "solidiom-btn--secondary",
      ghost: "solidiom-btn--ghost",
      link: "solidiom-btn--link",
    },
    size: {
      sm: "solidiom-btn--sm",
      md: "solidiom-btn--md",
      lg: "solidiom-btn--lg",
      icon: "solidiom-btn--icon",
    },
  },
  defaultVariants: {
    variant: "default",
    size: "md",
  },
  compoundVariants: [
    {
      variant: "ghost",
      size: "icon",
      class: "solidiom-btn--ghost-icon",
    },
    {
      variant: "link",
      size: "md",
      class: "solidiom-btn--link-md",
    },
  ],
})

export type ButtonVariantProps = VariantProps<typeof buttonVariants>
