packages:
  - "packages/*"
  - "apps/*"
  - "registry/*"
  - "tests/*"
  - "tools/*"
  - "templates/*"

catalog:
  solid-js: "^2.0.0-beta.32"
  "@solidjs/web": "^2.0.0-beta.32"
  babel-preset-solid: "^2.0.0-beta.32"

overrides:
  solid-js: "2.0.0-beta.32"
  "@solidjs/web": "2.0.0-beta.32"
  babel-preset-solid: "2.0.0-beta.32"

peerDependencyRules:
  allowAny:
    - "solid-js"
    - "@solidjs/web"
    - "babel-preset-solid"

onlyBuiltDependencies:
  - "esbuild"
  - "nx"
