import type { ThemeDefinition } from "../../../../../tools/theme-contract-schema"
import { resolveTokenValue, allDeclaredTokens } from "../../../../../tools/theme-contract-schema"
import type { BuilderExportFormat } from "../analytics-types"

export type ExportFormat = BuilderExportFormat

export function exportToJson(theme: ThemeDefinition): string {
  return JSON.stringify(theme, null, 2)
}

export function exportToCss(theme: ThemeDefinition): string {
  const { name, slug } = theme.meta
  const parts: string[] = [
    `/* Theme: ${name} — ${slug} */`,
    "/* Generated by Solidiom Theme Builder */",
    "",
  ]

  for (const mode of ["light", "dark"] as const) {
    const selector =
      mode === "light" ? ':root,\n:root[data-theme="light"]' : ':root[data-theme="dark"]'

    parts.push(`${selector} {`)

    const tokens = theme.modes[mode]
    if (tokens) {
      for (const [tokenId] of Object.entries(tokens)) {
        const resolved = resolveTokenValue(theme, mode, tokenId)
        if (resolved === undefined) continue
        parts.push(`  --sol-${tokenId}: ${resolved};`)
      }
    }

    parts.push("}")
    parts.push("")
  }

  return parts.join("\n")
}

function tailwindNamespace(tokenId: string): string {
  const category = tokenId.split("-")[0]
  switch (category) {
    case "surface":
    case "foreground":
    case "primary":
    case "secondary":
    case "destructive":
    case "success":
    case "warning":
    case "danger":
    case "info":
    case "accent":
    case "muted":
    case "overlay":
    case "input":
      return "color"
    case "radius":
      return "radius"
    case "shadow":
      return "shadow"
    case "border":
      return "color"
    case "focus":
      if (tokenId === "focus-ring") return "color"
      return "spacing"
    default:
      return "color"
  }
}

export function exportToTailwind(theme: ThemeDefinition): string {
  const { name, slug } = theme.meta
  const parts: string[] = [
    `/* Theme: ${name} — ${slug} */`,
    "/* Generated by Solidiom Theme Builder */",
    "@theme {",
  ]

  const tokenIds = allDeclaredTokens(theme)

  for (const tokenId of tokenIds) {
    const ns = tailwindNamespace(tokenId)
    const resolvedLight = resolveTokenValue(theme, "light", tokenId)
    if (resolvedLight === undefined) continue

    if (ns === "color") {
      parts.push(`  --color-${tokenId}: var(--sol-${tokenId}, ${resolvedLight});`)
    } else if (ns === "radius") {
      parts.push(
        `  --radius-${tokenId === "radius" ? "" : tokenId}: var(--sol-${tokenId}, ${resolvedLight});`,
      )
    } else if (ns === "shadow") {
      parts.push(`  --shadow-${tokenId}: var(--sol-${tokenId}, ${resolvedLight});`)
    } else {
      parts.push(`  --${tokenId}: var(--sol-${tokenId}, ${resolvedLight});`)
    }
  }

  parts.push("}")
  parts.push("")

  return parts.join("\n")
}

export function exportToUnoCss(theme: ThemeDefinition): string {
  return exportToCss(theme)
}

export function exportTheme(theme: ThemeDefinition, format: ExportFormat): string {
  switch (format) {
    case "json":
      return exportToJson(theme)
    case "css":
      return exportToCss(theme)
    case "tailwind":
      return exportToTailwind(theme)
    case "unocss":
      return exportToUnoCss(theme)
  }
}
