/**
 * GENERATED by tools/theme-emit-unocss.ts from tools/recipe-contract-definitions.ts ("unocss-preset")
 * Do not edit by hand — edit the definition and re-run the emitter.
 */

/** One theme's `--ui-*` variable assignments, ready to splice into UnoCSS's `preflights` array. */
export interface UnocssThemePreflight {
  slug: string
  name: string
  /** Raw CSS text: `[data-theme]`-scoped `--ui-*` custom property assignments. */
  css: string
}

/** Generated from tools/theme-contract-definitions.ts's REFERENCE_THEMES (THEME-004). */
export const SOLIDIOM_THEME_PREFLIGHTS: UnocssThemePreflight[] = [
  {
    slug: "solidiom-default",
    name: "Solidiom Default",
    css: ':root,\n:root[data-theme="light"] {\n  --ui-border: #CBD5E1;\n  --ui-destructive: #E5484D;\n  --ui-fg: #111827;\n  --ui-focus-ring: #5750D6;\n  --ui-muted-fg: #334155;\n  --ui-primary: #5750D6;\n  --ui-primary-fg: #FFFFFF;\n  --ui-primary-hover: #4C46C5;\n  --ui-radius: 12px;\n  --ui-radius-full: 999px;\n  --ui-radius-lg: 16px;\n  --ui-radius-sm: 8px;\n  --ui-secondary: #2563EB;\n  --ui-shadow-lg: 0 8px 24px -4px rgba(15, 23, 42, 0.08), 0 2px 8px -4px rgba(15, 23, 42, 0.04);\n  --ui-shadow-md: 0 2px 6px -1px rgba(15, 23, 42, 0.06), 0 1px 4px -2px rgba(15, 23, 42, 0.04);\n  --ui-shadow-sm: 0 1px 2px 0 rgba(15, 23, 42, 0.04);\n  --ui-success-fg: #22C55E;\n  --ui-surface: #F8FAFC;\n  --ui-surface-overlay: #FFFFFF;\n  --ui-warning-fg: #F59E0B;\n}\n\n:root[data-theme="dark"] {\n  --ui-border: #334155;\n  --ui-destructive: #F87171;\n  --ui-fg: #F1F5F9;\n  --ui-focus-ring: #8B83F8;\n  --ui-muted-fg: #94A3B8;\n  --ui-primary: #8B83F8;\n  --ui-primary-fg: #0F172A;\n  --ui-primary-hover: #A19BFA;\n  --ui-radius: 12px;\n  --ui-radius-full: 999px;\n  --ui-radius-lg: 16px;\n  --ui-radius-sm: 8px;\n  --ui-secondary: #60A5FA;\n  --ui-shadow-lg: 0 10px 30px -4px rgba(0, 0, 0, 0.4), 0 4px 10px -4px rgba(0, 0, 0, 0.25);\n  --ui-shadow-md: 0 3px 8px -1px rgba(0, 0, 0, 0.3), 0 1px 4px -2px rgba(0, 0, 0, 0.2);\n  --ui-shadow-sm: 0 1px 3px 0 rgba(0, 0, 0, 0.2);\n  --ui-success-fg: #4ADE80;\n  --ui-surface: #0F172A;\n  --ui-surface-overlay: #1E293B;\n  --ui-warning-fg: #FBBF24;\n}',
  },
]

/** Looks up a shipped theme's preflight by slug. */
export function themePreflight(slug: string): UnocssThemePreflight | undefined {
  return SOLIDIOM_THEME_PREFLIGHTS.find((theme) => theme.slug === slug)
}
