/**
 * GENERATED by tools/recipe-emit-unocss.ts from tools/recipe-contract-definitions.ts ("unocss-preset")
 * Do not edit by hand — edit the definition and re-run the emitter.
 */

/** UnoCSS static rule shape: `[matcher, declarations]`, https://unocss.dev/config/rules. */
export type UnocssStaticRule = [string, Record<string, string>]

/**
 * One static rule per variant/compound class name across every canonical recipe
 * definition with a `variants` axis. See packages/unocss-preset/src/index.ts for
 * how the preset consumes this.
 */
export const SOLIDIOM_VARIANT_RULES: UnocssStaticRule[] = [
  [
    "solidiom-badge--default",
    {
      "background-color": "var(--ui-primary, hsl(222 47% 11%))",
      color: "var(--ui-primary-fg, hsl(0 0% 100%))",
    },
  ],
  [
    "solidiom-badge--secondary",
    {
      "background-color": "var(--ui-secondary, hsl(210 40% 96%))",
      color: "var(--ui-secondary-fg, hsl(222 47% 11%))",
    },
  ],
  [
    "solidiom-badge--destructive",
    {
      "background-color": "var(--ui-destructive, hsl(0 84% 60%))",
      color: "var(--ui-destructive-fg, hsl(0 0% 100%))",
    },
  ],
  [
    "solidiom-badge--outline",
    {
      color: "var(--ui-fg, hsl(222 47% 11%))",
      "border-color": "var(--ui-border, hsl(214 32% 91%))",
      "background-color": "transparent",
    },
  ],
  [
    "solidiom-btn--default",
    {
      "background-color": "var(--ui-primary, hsl(222 47% 11%))",
      color: "var(--ui-primary-fg, hsl(0 0% 100%))",
    },
  ],
  [
    "solidiom-btn--destructive",
    {
      "background-color": "var(--ui-destructive, hsl(0 84% 60%))",
      color: "var(--ui-destructive-fg, hsl(0 0% 100%))",
    },
  ],
  [
    "solidiom-btn--outline",
    {
      "background-color": "transparent",
      color: "var(--ui-fg, hsl(222 47% 11%))",
      "border-style": "solid",
      "border-width": "1px",
      "border-color": "var(--ui-border, hsl(214 32% 91%))",
    },
  ],
  [
    "solidiom-btn--secondary",
    {
      "background-color": "var(--ui-secondary, hsl(210 40% 96%))",
      color: "var(--ui-secondary-fg, hsl(222 47% 11%))",
    },
  ],
  [
    "solidiom-btn--ghost",
    {
      "background-color": "transparent",
      color: "var(--ui-fg, hsl(222 47% 11%))",
    },
  ],
  [
    "solidiom-btn--link",
    {
      "background-color": "transparent",
      color: "var(--ui-primary, hsl(222 47% 11%))",
      "text-decoration-line": "underline",
      "text-underline-offset": "4px",
    },
  ],
  [
    "solidiom-btn--sm",
    {
      height: "2.25rem",
      padding: "0 0.75rem",
      "font-size": "0.875rem",
    },
  ],
  [
    "solidiom-btn--md",
    {
      height: "2.5rem",
      padding: "0.5rem 1rem",
      "font-size": "0.875rem",
    },
  ],
  [
    "solidiom-btn--lg",
    {
      height: "2.75rem",
      padding: "0 2rem",
      "font-size": "1rem",
    },
  ],
  [
    "solidiom-btn--icon",
    {
      height: "2.5rem",
      width: "2.5rem",
      padding: "0",
    },
  ],
  [
    "solidiom-btn--ghost-icon",
    {
      "border-radius": "var(--ui-radius-full, 9999px)",
    },
  ],
  [
    "solidiom-btn--link-md",
    {
      height: "auto",
      padding: "0",
    },
  ],
]
