/**
 * @solidiom/unocss-preset — UnoCSS variants for the Solidiom semantic attribute surface.
 *
 * Variants are generated from `@solidiom/runtime`'s semantic vocabulary rather than a
 * hand-maintained list, so the preset cannot drift from what primitives actually emit
 * (RECIPE-001b). Previously this file declared 11 variants by hand and was missing
 * `readonly` and `loading` entirely.
 *
 * Generated variants:
 *   - one per boolean flag — `uiDisabled` → `[data-disabled]`
 *   - one per distinct `data-state` value — `uiOpen` → `[data-state='open']`
 *   - one per orientation and side — `uiVertical`, `uiSideTop`
 *
 * Every variant matches on the element itself. UnoCSS cannot express an ancestor's
 * state, which is why the recipe contract requires each part to carry its own
 * `data-state` (docs/contracts/recipe-authoring-guide.md §3.2).
 *
 * RULES (RECIPE-004): the preset also ships static UnoCSS rules — `[className,
 * declarations]` pairs, https://unocss.dev/config/rules — for every variant and
 * compound-variant class name the canonical recipe definitions produce. This lets a
 * consumer write `class="solidiom-btn--destructive"` directly without importing
 * `@solidiom/recipes-unocss/styles/button.css`, resolving through UnoCSS's own
 * atomic-CSS generation instead of a separate stylesheet import.
 *
 * `./generated-variant-rules.ts` is generated by `tools/recipe-emit-unocss.ts` from
 * `tools/recipe-contract-definitions.ts` — the same source the stylesheets in
 * `@solidiom/recipes-unocss` come from — so this package does not depend on `tools/`
 * at runtime (`tools/` is not a published package). Re-run the emitter after a
 * definition changes; `pnpm run recipe:emit:unocss:check` fails otherwise.
 */
import {
  SEMANTIC_FLAGS,
  SEMANTIC_ORIENTATIONS,
  SEMANTIC_SIDES,
  allStateValues,
} from "@solidiom/runtime"
import { SOLIDIOM_VARIANT_RULES, type UnocssStaticRule } from "./generated-variant-rules"
import {
  SOLIDIOM_THEME_PREFLIGHTS,
  themePreflight,
  type UnocssThemePreflight,
} from "./generated-theme-preflights"

export interface SolidiomPresetOptions {
  /** Prefix for variant names. Default: "ui". */
  prefix?: string
  /**
   * Shipped theme slug (THEME-004) whose `--ui-*` variable assignments should be
   * injected as a UnoCSS preflight. Omit to install no theme — recipes then fall back
   * to their own hardcoded `var(--ui-x, fallback)` literal, matching the CSS profile's
   * unthemed baseline (RECIPE-002 §4).
   */
  theme?: string
}

/** Variant definitions mapping variant name to CSS selector. */
export interface VariantDefinition {
  name: string
  selector: string
}

export type { UnocssStaticRule }
export { SOLIDIOM_THEME_PREFLIGHTS, themePreflight, type UnocssThemePreflight }

/** `data-state` values that collide with a boolean flag of the same name. */
const FLAG_NAMES: ReadonlySet<string> = new Set(SEMANTIC_FLAGS)

/** `sorted-asc` → `SortedAsc` */
function pascalCase(value: string): string {
  return value
    .split("-")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("")
}

/**
 * Returns the Solidiom UnoCSS preset variant definitions.
 *
 * A state value that collides with a boolean flag (`disabled`, `loading`, `selected`)
 * is namespaced as `uiStateSelected` so the bare `uiSelected` keeps targeting the
 * flag. Those collisions are the vocabulary exceptions recorded in
 * `VOCABULARY_EXCEPTIONS`; when the owning primitives stop emitting a flag as a
 * state, the namespaced variants disappear on their own.
 */
export function getSolidiomVariants(options: SolidiomPresetOptions = {}): VariantDefinition[] {
  const p = options.prefix ?? "ui"

  const flagVariants = SEMANTIC_FLAGS.map((flag) => ({
    name: `${p}${pascalCase(flag)}`,
    selector: `[data-${flag}]`,
  }))

  const stateVariants = allStateValues().map((state) => ({
    name: FLAG_NAMES.has(state) ? `${p}State${pascalCase(state)}` : `${p}${pascalCase(state)}`,
    selector: `[data-state='${state}']`,
  }))

  const orientationVariants = SEMANTIC_ORIENTATIONS.map((orientation) => ({
    name: `${p}${pascalCase(orientation)}`,
    selector: `[data-orientation='${orientation}']`,
  }))

  const sideVariants = SEMANTIC_SIDES.map((side) => ({
    name: `${p}Side${pascalCase(side)}`,
    selector: `[data-side='${side}']`,
  }))

  return [...flagVariants, ...stateVariants, ...orientationVariants, ...sideVariants]
}

/** Generated static UnoCSS rules for every recipe variant/compound class name. */
export function getSolidiomVariantRules(): UnocssStaticRule[] {
  return SOLIDIOM_VARIANT_RULES
}

/**
 * Creates the UnoCSS preset object (compatible with UnoCSS defineConfig).
 *
 * When `options.theme` names a shipped slug, its `--ui-*` preflight CSS (THEME-004) is
 * included in the returned `preflights` array so a consumer does not need a separate
 * stylesheet import to theme every profile that reads the shared runtime namespace.
 */
export function presetSolidiom(options: SolidiomPresetOptions = {}) {
  const variants = getSolidiomVariants(options)
  const preflight = options.theme ? themePreflight(options.theme) : undefined
  return {
    name: "@solidiom/unocss-preset",
    variants: variants.map((v) => ({
      name: v.name,
      match: (input: string) => {
        if (!input.startsWith(`${v.name}:`)) return undefined
        return {
          matcher: input.slice(v.name.length + 1),
          selector: (s: string) => `${s}${v.selector}`,
        }
      },
    })),
    rules: getSolidiomVariantRules(),
    preflights: preflight ? [{ getCSS: () => preflight.css }] : [],
  }
}
