/**
 * @solidiom/primitives — Umbrella re-export of all Solidiom primitives.
 * Thin re-export only — no implementation code.
 */

export * as Accordion from "@solidiom/accordion"
export * as Alert from "@solidiom/alert"
export * as AlertDialog from "@solidiom/alert-dialog"
export * as Avatar from "@solidiom/avatar"
export * as Badge from "@solidiom/badge"
export * as Breadcrumb from "@solidiom/breadcrumb"
export * as Button from "@solidiom/button"
export * as Calendar from "@solidiom/calendar"
export * as Card from "@solidiom/card"
export * as Carousel from "@solidiom/carousel"
export * as Checkbox from "@solidiom/checkbox"
export * as Collapsible from "@solidiom/collapsible"
export * as Combobox from "@solidiom/combobox"
export * as CommandPalette from "@solidiom/command-palette"
export * as ContextMenu from "@solidiom/context-menu"
export * as DataTable from "@solidiom/data-table"
export * as DatePicker from "@solidiom/date-picker"
export * as Dialog from "@solidiom/dialog"
export * as Drawer from "@solidiom/drawer"
export * as EmptyState from "@solidiom/empty-state"
export * as Field from "@solidiom/field"
export * as HoverCard from "@solidiom/hover-card"
export * as Input from "@solidiom/input"
export * as InputOTP from "@solidiom/input-otp"
export * as Kbd from "@solidiom/kbd"
export * as Label from "@solidiom/label"
export * as Listbox from "@solidiom/listbox"
export * as Menu from "@solidiom/menu"
export * as Meter from "@solidiom/meter"
export * as NavigationMenu from "@solidiom/navigation-menu"
export * as Pagination from "@solidiom/pagination"
export * as Popover from "@solidiom/popover"
export * as Progress from "@solidiom/progress"
export * as RadioGroup from "@solidiom/radio-group"
export * as ResizablePanels from "@solidiom/resizable-panels"
export * as ScrollArea from "@solidiom/scroll-area"
export * as Select from "@solidiom/select"
export * as Separator from "@solidiom/separator"
export * as Sheet from "@solidiom/sheet"
export * as Skeleton from "@solidiom/skeleton"
export * as Slider from "@solidiom/slider"
export * as Spinner from "@solidiom/spinner"
export * as Switch from "@solidiom/switch"
export * as Tabs from "@solidiom/tabs"
export * as Toast from "@solidiom/toast"
export * as Toggle from "@solidiom/toggle"
export * as ToggleGroup from "@solidiom/toggle-group"
export * as Toolbar from "@solidiom/toolbar"
export * as Tooltip from "@solidiom/tooltip"
export * as Tree from "@solidiom/tree"
export * as VirtualList from "@solidiom/virtual-list"
export * as VisuallyHidden from "@solidiom/visually-hidden"


// Phase 1 — Form completeness
export * as NumberInput from "@solidiom/number-input"
export * as FileInput from "@solidiom/file-input"
export * as DateRangeInput from "@solidiom/date-range-input"
export * as TimeInput from "@solidiom/time-input"
export * as MultiSelector from "@solidiom/multi-selector"
export * as Tokenizer from "@solidiom/tokenizer"
export * as InputGroup from "@solidiom/input-group"

// Phase 2 — Layout & Navigation
export * as Stack from "@solidiom/stack"
export * as Grid from "@solidiom/grid"
export * as AspectRatio from "@solidiom/aspect-ratio"
export * as Sidebar from "@solidiom/sidebar"
export * as AppShell from "@solidiom/app-shell"
export * as MegaMenu from "@solidiom/mega-menu"
export * as SegmentedControl from "@solidiom/segmented-control"

// Phase 3 — Content & Display
export * as Table from "@solidiom/table"
export * as AvatarGroup from "@solidiom/avatar-group"
export * as Typography from "@solidiom/typography"
export * as CodeBlock from "@solidiom/code-block"
export * as Banner from "@solidiom/banner"
export * as StatusDot from "@solidiom/status-dot"
export * as Link from "@solidiom/link"

// Phase 4 — Chat / AI
export * as ChatMessage from "@solidiom/chat-message"
export * as ChatComposer from "@solidiom/chat-composer"
export * as ChatLayout from "@solidiom/chat-layout"
export * as ChatMessageMetadata from "@solidiom/chat-message-metadata"
export * as ChatSystemMessage from "@solidiom/chat-system-message"
export * as ChatToolCalls from "@solidiom/chat-tool-calls"
export * as MessageScroller from "@solidiom/message-scroller"

// Phase 5 — Polish
export * as Lightbox from "@solidiom/lightbox"
export * as Direction from "@solidiom/direction"
export * as Chart from "@solidiom/chart"
export * as Questionnaire from "@solidiom/questionnaire"
export * as Attachment from "@solidiom/attachment"
export * as Menubar from "@solidiom/menubar"
