/**
 * GENERATED by tools/recipe-emit-tailwind.ts from tools/recipe-contract-definitions.ts ("button")
 * Do not edit by hand — edit the definition and re-run the emitter.
 */

import { cva, type VariantProps } from "class-variance-authority"
import { twMerge } from "tailwind-merge"

const buttonVariantsCva = cva(
  "inline-flex items-center justify-center gap-2 whitespace-nowrap border-none font-medium cursor-pointer rounded-radius transition-all",
  {
    variants: {
      variant: {
        default: "bg-primary text-primary-foreground",
        destructive: "bg-destructive text-destructive-foreground",
        outline: "bg-transparent text-foreground border-solid border-border",
        secondary: "bg-secondary text-secondary-foreground",
        ghost: "bg-transparent text-foreground",
        link: "bg-transparent text-primary underline underline-offset-4",
      },
      size: {
        sm: "h-9 py-0 px-3 text-sm",
        md: "h-10 py-2 px-4 text-sm",
        lg: "h-11 py-0 px-8 text-base",
        icon: "h-10 w-10 p-0",
      },
    },
    defaultVariants: {
      variant: "default",
      size: "md",
    },
    compoundVariants: [
      {
        variant: "ghost",
        size: "icon",
        class: "rounded-radius-full",
      },
      {
        variant: "link",
        size: "md",
        class: "h-auto p-0",
      },
    ],
  },
)

export type ButtonVariantProps = VariantProps<typeof buttonVariantsCva>

/**
 * buttonVariantsCva() concatenates each matched variant/compound's utilities in
 * declaration order; it does not resolve a later utility overriding an earlier
 * one on the same CSS property, because Tailwind's compiled stylesheet orders
 * utilities by its own internal grouping and scale value, not by the order
 * classes appear in a class string (docs/contracts/recipe-contract.md §6).
 * twMerge() reconciles that: it understands Tailwind's utility groups and
 * keeps only the last conflicting class for a given property, matching what
 * this scope's cascade-based css/unocss stylesheets already produce.
 */
export function buttonVariants(props?: ButtonVariantProps): string {
  return twMerge(buttonVariantsCva(props))
}
