/**
 * GENERATED by tools/recipe-emit-tailwind.ts from tools/recipe-contract-definitions.ts ("button")
 * Do not edit by hand — edit the definition and re-run the emitter.
 */

import { cva, type VariantProps } from "class-variance-authority"

export const buttonVariants = cva(
  "inline-flex items-center justify-center gap-2 whitespace-nowrap border-none font-medium cursor-pointer rounded-radius transition-all",
  {
    variants: {
      variant: {
        default: "bg-primary text-primary-foreground",
        destructive: "bg-destructive text-destructive-foreground",
        outline: "bg-transparent text-foreground border-solid border-border",
        secondary: "bg-secondary text-secondary-foreground",
        ghost: "bg-transparent text-foreground",
        link: "bg-transparent text-primary underline underline-offset-4",
      },
      size: {
        sm: "h-9 py-0 px-3 text-sm",
        md: "h-10 py-2 px-4 text-sm",
        lg: "h-11 py-0 px-8 text-base",
        icon: "h-10 w-10 py-0 px-0",
      },
    },
    defaultVariants: {
      variant: "default",
      size: "md",
    },
    compoundVariants: [
      {
        variant: "ghost",
        size: "icon",
        class: "rounded-radius-full",
      },
      {
        variant: "link",
        size: "md",
        class: "h-auto py-0 px-0",
      },
    ],
  },
)

export type ButtonVariantProps = VariantProps<typeof buttonVariants>
