storage: ./storage
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
packages:
  "@solidiom/*":
    access: $all
    publish: $authenticated
    proxy: npmjs
  "**":
    access: $all
    proxy: npmjs
server:
  keepAliveTimeout: 60
listen: 0.0.0.0:4873
