import { describe, expect, it } from "vitest"
import { readFileSync, existsSync } from "node:fs"
import { join } from "node:path"
import { emitTailwind } from "./recipe-emit-tailwind"
import { REFERENCE_DEFINITIONS } from "./recipe-contract-definitions"

const ROOT = join(import.meta.dirname ?? __dirname, "..")
const STYLES_DIR = join(ROOT, "packages/recipes-tailwind/src/styles")
const RECIPES_DIR = join(ROOT, "packages/recipes-tailwind/src/recipes")

describe("recipe-emit-tailwind", () => {
  it("check mode reports up to date against the committed output", async () => {
    const upToDate = await emitTailwind({ check: true })
    expect(upToDate).toBe(true)
  })

  it("emits an @layer components stylesheet for every reference definition", () => {
    for (const scope of Object.keys(REFERENCE_DEFINITIONS)) {
      const css = readFileSync(join(STYLES_DIR, `${scope}.css`), "utf8")
      expect(css, `${scope}.css`).toContain("@layer components")
      expect(css, `${scope}.css`).toContain(`[data-scope="${scope}"]`)
      expect(css, `${scope}.css`).toContain("GENERATED by tools/recipe-emit-tailwind.ts")
      expect(css, `${scope}.css`).toContain("@apply")
    }
  })

  it("switch styles state on the part that carries it, not an ancestor selector", () => {
    const css = readFileSync(join(STYLES_DIR, "switch.css"), "utf8")
    expect(css).not.toMatch(/\[data-part="root"\]\[data-state="on"\]\s+\[data-part="thumb"\]/)
    expect(css).toContain('[data-scope="switch"][data-part="thumb"][data-state="on"]')
  })

  it("merges a base rule and its pseudo rule into one selector block", () => {
    const css = readFileSync(join(STYLES_DIR, "switch.css"), "utf8")
    const rootBlocks = [...css.matchAll(/\[data-scope="switch"\]\[data-part="root"\] \{/g)]
    expect(rootBlocks).toHaveLength(1)
    expect(css).toContain("focus-visible:outline")
  })

  it("button backs every variant and compound with a data-qualified class selector using real utilities", () => {
    const css = readFileSync(join(STYLES_DIR, "button.css"), "utf8")
    expect(css).toContain('[data-part="root"].solidiom-btn--destructive')
    expect(css).toContain("bg-destructive")
    expect(css).toContain('[data-part="root"].solidiom-btn--ghost-icon')
    expect(css).not.toMatch(/^\s*\.[a-zA-Z]/m)
  })

  it("generates a cva module for button using real Tailwind utilities, not solidiom-btn-- classes", () => {
    const variants = readFileSync(join(RECIPES_DIR, "button.variants.ts"), "utf8")
    expect(variants).toContain("bg-destructive")
    expect(variants).not.toContain("solidiom-btn--")
  })

  it("alert has no generated variants module (its variants come from data-state)", () => {
    expect(existsSync(join(RECIPES_DIR, "alert.variants.ts"))).toBe(false)
  })

  it("does not generate or overwrite the hand-maintained theme.css", () => {
    const theme = readFileSync(join(STYLES_DIR, "theme.css"), "utf8")
    expect(theme).not.toContain("GENERATED by tools/recipe-emit-tailwind.ts")
  })

  it("regenerates styles/index.css importing theme.css first, then every scope, then utility stylesheets", () => {
    const index = readFileSync(join(STYLES_DIR, "index.css"), "utf8")
    const lines = index.split("\n").filter((line) => line.startsWith("@import"))
    expect(lines[0]).toBe('@import "./theme.css";')
    for (const scope of Object.keys(REFERENCE_DEFINITIONS)) {
      expect(index).toContain(`@import "./${scope}.css";`)
    }
    expect(index).toContain('@import "./typeset.css";')
    expect(index).toContain('@import "./prose.css";')
  })
})
