import { describe, expect, it } from "vitest"
import { readFileSync } from "node:fs"
import { join } from "node:path"
import { emitCss } from "./recipe-emit-css"
import { REFERENCE_DEFINITIONS } from "./recipe-contract-definitions"

const ROOT = join(import.meta.dirname ?? __dirname, "..")
const STYLES_DIR = join(ROOT, "packages/recipes-css/src/styles")
const RECIPES_DIR = join(ROOT, "packages/recipes-css/src/recipes")

describe("recipe-emit-css", () => {
  it("check mode reports up to date against the committed output", async () => {
    const upToDate = await emitCss({ check: true })
    expect(upToDate).toBe(true)
  })

  it("emits a stylesheet for every reference definition", () => {
    for (const scope of Object.keys(REFERENCE_DEFINITIONS)) {
      const css = readFileSync(join(STYLES_DIR, `${scope}.css`), "utf8")
      expect(css, `${scope}.css`).toContain(`[data-scope="${scope}"]`)
      expect(css, `${scope}.css`).toContain("GENERATED by tools/recipe-emit-css.ts")
    }
  })

  it("switch styles state on the part that carries it, not an ancestor selector", () => {
    const css = readFileSync(join(STYLES_DIR, "switch.css"), "utf8")
    expect(css).not.toMatch(/\[data-part="root"\]\[data-state="on"\]\s+\[data-part="thumb"\]/)
    expect(css).toContain('[data-scope="switch"][data-part="thumb"][data-state="on"]')
  })

  it("button backs every variant and compound with a data-qualified class selector", () => {
    const css = readFileSync(join(STYLES_DIR, "button.css"), "utf8")
    expect(css).toContain('[data-part="root"].solidiom-btn--destructive')
    expect(css).toContain('[data-part="root"].solidiom-btn--ghost-icon')
    // No unqualified class selector — every class selector is preceded by a
    // [data-part=...] attribute selector on the same rule.
    expect(css).not.toMatch(/^\s*\.[a-zA-Z]/m)
  })

  it("generates a cva module for button whose classes match the stylesheet's selectors", () => {
    const variants = readFileSync(join(RECIPES_DIR, "button.variants.ts"), "utf8")
    const css = readFileSync(join(STYLES_DIR, "button.css"), "utf8")
    const classNames = [...variants.matchAll(/"(solidiom-btn--[a-z-]+)"/g)].map((m) => m[1])
    expect(classNames.length).toBeGreaterThan(0)
    for (const className of new Set(classNames)) {
      expect(css, `button.css must define a selector for .${className}`).toContain(`.${className}`)
    }
  })

  it("alert has no generated variants module (its variants come from data-state)", async () => {
    const { existsSync } = await import("node:fs")
    expect(existsSync(join(RECIPES_DIR, "alert.variants.ts"))).toBe(false)
  })

  it("regenerates styles/index.css with an @import per scope plus utility stylesheets", () => {
    const index = readFileSync(join(STYLES_DIR, "index.css"), "utf8")
    for (const scope of Object.keys(REFERENCE_DEFINITIONS)) {
      expect(index).toContain(`@import "./${scope}.css";`)
    }
    expect(index).toContain('@import "./typeset.css";')
    expect(index).toContain('@import "./prose.css";')
  })
})
