/**
 * tools/theme-contract-definitions — reference theme definitions (THEME-001f).
 *
 * `solidiom-default` restates the exact colour/radius/shadow values already shipped in
 * `apps/site/src/assets/tokens.css` (BRAND-002) as a canonical `ThemeDefinition`, so:
 *
 *   - `pnpm run theme:contract` has a real, non-trivial definition to validate;
 *   - THEME-002/003/004's generators have a first input to generate CSS/Tailwind/UnoCSS
 *     output from and diff against the hand-written `tokens.css` for drift;
 *   - PRESET-001..004 have a working example to model additional presets on.
 *
 * This does not replace `tokens.css`. BRAND-002's hand-written stylesheet remains the
 * shipped site theme until THEME-002 generates it from this document; until then, this
 * file's values are kept in sync with `tokens.css` by inspection (see
 * `tools/theme-contract-definitions.test.ts`, which reads `tokens.css` and asserts the
 * two do not drift).
 *
 * `focus-ring-width` and `foreground-subtle`/`foreground-inverse`/`border-muted`/
 * `border-active`/`surface-sunken` are declared even though they sit outside
 * `REQUIRED_BASELINE_TOKENS`, because `tokens.css` already authors all of them and a
 * reference theme should demonstrate a fuller token set than the bare minimum.
 */
import { THEME_SCHEMA_VERSION, type ThemeDefinition } from "./theme-contract-schema"

export const SOLIDIOM_DEFAULT_THEME: ThemeDefinition = {
  schemaVersion: THEME_SCHEMA_VERSION,
  meta: {
    name: "Solidiom Default",
    slug: "solidiom-default",
    description:
      "The canonical Solidiom theme: a cool slate canvas in light mode and a deep slate base in dark mode, both built around the indigo primary.",
    kind: "preset",
    author: "Solidiom",
  },
  modes: {
    light: {
      surface: "#F8FAFC",
      "surface-raised": "#FFFFFF",
      "surface-overlay": "#FFFFFF",
      "surface-sunken": "#F1F5F9",
      foreground: "#111827",
      "foreground-muted": "#334155",
      "foreground-subtle": "#64748B",
      "foreground-inverse": "#F8FAFC",
      border: "#CBD5E1",
      "border-muted": "#E2E8F0",
      "border-active": "#5750D6",
      primary: "#5750D6",
      "primary-hover": "#4C46C5",
      "primary-foreground": "#FFFFFF",
      secondary: "#2563EB",
      success: "#22C55E",
      warning: "#F59E0B",
      destructive: "#E5484D",
      "focus-ring": { ref: "primary" },
      "focus-ring-width": "2px",
      "radius-sm": "8px",
      radius: "12px",
      "radius-lg": "16px",
      "radius-full": "999px",
      "shadow-sm": "0 1px 2px 0 rgba(15, 23, 42, 0.04)",
      "shadow-md": "0 2px 6px -1px rgba(15, 23, 42, 0.06), 0 1px 4px -2px rgba(15, 23, 42, 0.04)",
      "shadow-lg": "0 8px 24px -4px rgba(15, 23, 42, 0.08), 0 2px 8px -4px rgba(15, 23, 42, 0.04)",
      "font-size-xs": "0.75rem",
      "line-height-xs": "1rem",
      "font-size-sm": "0.875rem",
      "line-height-sm": "1.25rem",
      "font-size-base": "0.875rem",
      "line-height-base": "1.25rem",
      "font-size-md": "1.125rem",
      "line-height-md": "1.5rem",
      "font-size-lg": "1.25rem",
      "line-height-lg": "1.5rem",
      "font-size-xl": "1.875rem",
      "line-height-xl": "2.25rem",
    },
    dark: {
      surface: "#0F172A",
      "surface-raised": "#1E293B",
      "surface-overlay": "#1E293B",
      "surface-sunken": "#020617",
      foreground: "#F1F5F9",
      "foreground-muted": "#94A3B8",
      "foreground-subtle": "#64748B",
      "foreground-inverse": "#0F172A",
      border: "#334155",
      "border-muted": "#1E293B",
      "border-active": "#8B83F8",
      primary: "#8B83F8",
      "primary-hover": "#A19BFA",
      "primary-foreground": "#0F172A",
      secondary: "#60A5FA",
      success: "#4ADE80",
      warning: "#FBBF24",
      destructive: "#F87171",
      "focus-ring": { ref: "primary" },
      "focus-ring-width": "2px",
      "radius-sm": "8px",
      radius: "12px",
      "radius-lg": "16px",
      "radius-full": "999px",
      "shadow-sm": "0 1px 3px 0 rgba(0, 0, 0, 0.2)",
      "shadow-md": "0 3px 8px -1px rgba(0, 0, 0, 0.3), 0 1px 4px -2px rgba(0, 0, 0, 0.2)",
      "shadow-lg": "0 10px 30px -4px rgba(0, 0, 0, 0.4), 0 4px 10px -4px rgba(0, 0, 0, 0.25)",
      "font-size-xs": "0.75rem",
      "line-height-xs": "1rem",
      "font-size-sm": "0.875rem",
      "line-height-sm": "1.25rem",
      "font-size-base": "0.875rem",
      "line-height-base": "1.25rem",
      "font-size-md": "1.125rem",
      "line-height-md": "1.5rem",
      "font-size-lg": "1.25rem",
      "line-height-lg": "1.5rem",
      "font-size-xl": "1.875rem",
      "line-height-xl": "2.25rem",
    },
  },
}

/**
 * PRESET-001: Ocean — deep teal primary with cyan accents.
 * Light mode: crisp white canvas with ocean blue.
 * Dark mode: deep navy with teal highlights.
 */
export const OCEAN_THEME: ThemeDefinition = {
  schemaVersion: THEME_SCHEMA_VERSION,
  meta: {
    name: "Ocean",
    slug: "ocean",
    description:
      "Deep teal primary with cyan accents — a cool, aquatic palette with high contrast and calm neutrals.",
    kind: "preset",
    author: "Solidiom",
  },
  modes: {
    light: {
      surface: "#F0F9FF",
      "surface-raised": "#FFFFFF",
      "surface-overlay": "#FFFFFF",
      "surface-sunken": "#E0F2FE",
      foreground: "#0C2D48",
      "foreground-muted": "#334E68",
      "foreground-subtle": "#5F7592",
      "foreground-inverse": "#F0F9FF",
      border: "#9DB4C0",
      "border-muted": "#C2D4DF",
      "border-active": "#0B7285",
      primary: "#0B7285",
      "primary-hover": "#0A5F71",
      "primary-foreground": "#FFFFFF",
      secondary: "#0284C7",
      success: "#059669",
      warning: "#D97706",
      destructive: "#DC2626",
      "focus-ring": { ref: "primary" },
      "focus-ring-width": "2px",
      "radius-sm": "8px",
      radius: "12px",
      "radius-lg": "16px",
      "radius-full": "999px",
      "shadow-sm": "0 1px 2px 0 rgba(12, 45, 72, 0.04)",
      "shadow-md": "0 2px 6px -1px rgba(12, 45, 72, 0.06), 0 1px 4px -2px rgba(12, 45, 72, 0.04)",
      "shadow-lg": "0 8px 24px -4px rgba(12, 45, 72, 0.08), 0 2px 8px -4px rgba(12, 45, 72, 0.04)",
      "font-size-xs": "0.75rem",
      "line-height-xs": "1rem",
      "font-size-sm": "0.875rem",
      "line-height-sm": "1.25rem",
      "font-size-base": "0.875rem",
      "line-height-base": "1.25rem",
      "font-size-md": "1.125rem",
      "line-height-md": "1.5rem",
      "font-size-lg": "1.25rem",
      "line-height-lg": "1.5rem",
      "font-size-xl": "1.875rem",
      "line-height-xl": "2.25rem",
    },
    dark: {
      surface: "#0A1929",
      "surface-raised": "#132F4C",
      "surface-overlay": "#132F4C",
      "surface-sunken": "#050D18",
      foreground: "#E0F2FE",
      "foreground-muted": "#9DB4C0",
      "foreground-subtle": "#5F7592",
      "foreground-inverse": "#0A1929",
      border: "#234666",
      "border-muted": "#132F4C",
      "border-active": "#22D3EE",
      primary: "#22D3EE",
      "primary-hover": "#67E8F9",
      "primary-foreground": "#0A1929",
      secondary: "#38BDF8",
      success: "#34D399",
      warning: "#FBBF24",
      destructive: "#F87171",
      "focus-ring": { ref: "primary" },
      "focus-ring-width": "2px",
      "radius-sm": "8px",
      radius: "12px",
      "radius-lg": "16px",
      "radius-full": "999px",
      "shadow-sm": "0 1px 3px 0 rgba(0, 0, 0, 0.2)",
      "shadow-md": "0 3px 8px -1px rgba(0, 0, 0, 0.3), 0 1px 4px -2px rgba(0, 0, 0, 0.2)",
      "shadow-lg": "0 10px 30px -4px rgba(0, 0, 0, 0.4), 0 4px 10px -4px rgba(0, 0, 0, 0.25)",
      "font-size-xs": "0.75rem",
      "line-height-xs": "1rem",
      "font-size-sm": "0.875rem",
      "line-height-sm": "1.25rem",
      "font-size-base": "0.875rem",
      "line-height-base": "1.25rem",
      "font-size-md": "1.125rem",
      "line-height-md": "1.5rem",
      "font-size-lg": "1.25rem",
      "line-height-lg": "1.5rem",
      "font-size-xl": "1.875rem",
      "line-height-xl": "2.25rem",
    },
  },
}

/**
 * PRESET-002: Forest — moss green primary with warm earth tones.
 * Light mode: sage accents on cream.
 * Dark mode: deep forest green with amber highlights.
 */
export const FOREST_THEME: ThemeDefinition = {
  schemaVersion: THEME_SCHEMA_VERSION,
  meta: {
    name: "Forest",
    slug: "forest",
    description:
      "Moss green primary with warm earth tones — an organic palette with natural contrast and grounded neutrals.",
    kind: "preset",
    author: "Solidiom",
  },
  modes: {
    light: {
      surface: "#FAFAF5",
      "surface-raised": "#FFFFFF",
      "surface-overlay": "#FFFFFF",
      "surface-sunken": "#F0F0E8",
      foreground: "#1A2E05",
      "foreground-muted": "#4A5D3A",
      "foreground-subtle": "#6B7F5E",
      "foreground-inverse": "#FAFAF5",
      border: "#B5C4A6",
      "border-muted": "#D4DECB",
      "border-active": "#3E6B24",
      primary: "#3E6B24",
      "primary-hover": "#33581C",
      "primary-foreground": "#FFFFFF",
      secondary: "#5B8C3E",
      success: "#2D7A2D",
      warning: "#B45309",
      destructive: "#B91C1C",
      "focus-ring": { ref: "primary" },
      "focus-ring-width": "2px",
      "radius-sm": "8px",
      radius: "12px",
      "radius-lg": "16px",
      "radius-full": "999px",
      "shadow-sm": "0 1px 2px 0 rgba(26, 46, 5, 0.04)",
      "shadow-md": "0 2px 6px -1px rgba(26, 46, 5, 0.06), 0 1px 4px -2px rgba(26, 46, 5, 0.04)",
      "shadow-lg": "0 8px 24px -4px rgba(26, 46, 5, 0.08), 0 2px 8px -4px rgba(26, 46, 5, 0.04)",
      "font-size-xs": "0.75rem",
      "line-height-xs": "1rem",
      "font-size-sm": "0.875rem",
      "line-height-sm": "1.25rem",
      "font-size-base": "0.875rem",
      "line-height-base": "1.25rem",
      "font-size-md": "1.125rem",
      "line-height-md": "1.5rem",
      "font-size-lg": "1.25rem",
      "line-height-lg": "1.5rem",
      "font-size-xl": "1.875rem",
      "line-height-xl": "2.25rem",
    },
    dark: {
      surface: "#0F1A0A",
      "surface-raised": "#1A2E14",
      "surface-overlay": "#1A2E14",
      "surface-sunken": "#080F05",
      foreground: "#E8F0E0",
      "foreground-muted": "#9DB490",
      "foreground-subtle": "#6B7F5E",
      "foreground-inverse": "#0F1A0A",
      border: "#2D4A22",
      "border-muted": "#1A2E14",
      "border-active": "#86EFAC",
      primary: "#86EFAC",
      "primary-hover": "#BBF7D0",
      "primary-foreground": "#0F1A0A",
      secondary: "#4ADE80",
      success: "#4ADE80",
      warning: "#FBBF24",
      destructive: "#F87171",
      "focus-ring": { ref: "primary" },
      "focus-ring-width": "2px",
      "radius-sm": "8px",
      radius: "12px",
      "radius-lg": "16px",
      "radius-full": "999px",
      "shadow-sm": "0 1px 3px 0 rgba(0, 0, 0, 0.2)",
      "shadow-md": "0 3px 8px -1px rgba(0, 0, 0, 0.3), 0 1px 4px -2px rgba(0, 0, 0, 0.2)",
      "shadow-lg": "0 10px 30px -4px rgba(0, 0, 0, 0.4), 0 4px 10px -4px rgba(0, 0, 0, 0.25)",
      "font-size-xs": "0.75rem",
      "line-height-xs": "1rem",
      "font-size-sm": "0.875rem",
      "line-height-sm": "1.25rem",
      "font-size-base": "0.875rem",
      "line-height-base": "1.25rem",
      "font-size-md": "1.125rem",
      "line-height-md": "1.5rem",
      "font-size-lg": "1.25rem",
      "line-height-lg": "1.5rem",
      "font-size-xl": "1.875rem",
      "line-height-xl": "2.25rem",
    },
  },
}

/**
 * PRESET-003: Slate — neutral gray primary with blue undertones.
 * Light mode: cool gray with steel accents.
 * Dark mode: zinc-based with silver highlights.
 */
export const SLATE_THEME: ThemeDefinition = {
  schemaVersion: THEME_SCHEMA_VERSION,
  meta: {
    name: "Slate",
    slug: "slate",
    description:
      "Neutral gray primary with blue undertones — a sophisticated, corporate palette with steel accents.",
    kind: "preset",
    author: "Solidiom",
  },
  modes: {
    light: {
      surface: "#F8FAFC",
      "surface-raised": "#FFFFFF",
      "surface-overlay": "#FFFFFF",
      "surface-sunken": "#F1F5F9",
      foreground: "#0F172A",
      "foreground-muted": "#334155",
      "foreground-subtle": "#64748B",
      "foreground-inverse": "#F8FAFC",
      border: "#94A3B8",
      "border-muted": "#CBD5E1",
      "border-active": "#475569",
      primary: "#475569",
      "primary-hover": "#374151",
      "primary-foreground": "#FFFFFF",
      secondary: "#64748B",
      success: "#16A34A",
      warning: "#CA8A04",
      destructive: "#DC2626",
      "focus-ring": { ref: "primary" },
      "focus-ring-width": "2px",
      "radius-sm": "8px",
      radius: "12px",
      "radius-lg": "16px",
      "radius-full": "999px",
      "shadow-sm": "0 1px 2px 0 rgba(15, 23, 42, 0.04)",
      "shadow-md": "0 2px 6px -1px rgba(15, 23, 42, 0.06), 0 1px 4px -2px rgba(15, 23, 42, 0.04)",
      "shadow-lg": "0 8px 24px -4px rgba(15, 23, 42, 0.08), 0 2px 8px -4px rgba(15, 23, 42, 0.04)",
      "font-size-xs": "0.75rem",
      "line-height-xs": "1rem",
      "font-size-sm": "0.875rem",
      "line-height-sm": "1.25rem",
      "font-size-base": "0.875rem",
      "line-height-base": "1.25rem",
      "font-size-md": "1.125rem",
      "line-height-md": "1.5rem",
      "font-size-lg": "1.25rem",
      "line-height-lg": "1.5rem",
      "font-size-xl": "1.875rem",
      "line-height-xl": "2.25rem",
    },
    dark: {
      surface: "#0F172A",
      "surface-raised": "#1E293B",
      "surface-overlay": "#1E293B",
      "surface-sunken": "#020617",
      foreground: "#F1F5F9",
      "foreground-muted": "#94A3B8",
      "foreground-subtle": "#64748B",
      "foreground-inverse": "#0F172A",
      border: "#334155",
      "border-muted": "#1E293B",
      "border-active": "#94A3B8",
      primary: "#94A3B8",
      "primary-hover": "#CBD5E1",
      "primary-foreground": "#0F172A",
      secondary: "#64748B",
      success: "#4ADE80",
      warning: "#FBBF24",
      destructive: "#F87171",
      "focus-ring": { ref: "primary" },
      "focus-ring-width": "2px",
      "radius-sm": "8px",
      radius: "12px",
      "radius-lg": "16px",
      "radius-full": "999px",
      "shadow-sm": "0 1px 3px 0 rgba(0, 0, 0, 0.2)",
      "shadow-md": "0 3px 8px -1px rgba(0, 0, 0, 0.3), 0 1px 4px -2px rgba(0, 0, 0, 0.2)",
      "shadow-lg": "0 10px 30px -4px rgba(0, 0, 0, 0.4), 0 4px 10px -4px rgba(0, 0, 0, 0.25)",
      "font-size-xs": "0.75rem",
      "line-height-xs": "1rem",
      "font-size-sm": "0.875rem",
      "line-height-sm": "1.25rem",
      "font-size-base": "0.875rem",
      "line-height-base": "1.25rem",
      "font-size-md": "1.125rem",
      "line-height-md": "1.5rem",
      "font-size-lg": "1.25rem",
      "line-height-lg": "1.5rem",
      "font-size-xl": "1.875rem",
      "line-height-xl": "2.25rem",
    },
  },
}

/**
 * PRESET-004: Aurora — purple-violet primary with warm accents.
 * Light mode: lavender accents on white.
 * Dark mode: vivid purple with pink highlights.
 */
export const AURORA_THEME: ThemeDefinition = {
  schemaVersion: THEME_SCHEMA_VERSION,
  meta: {
    name: "Aurora",
    slug: "aurora",
    description:
      "Purple-violet primary with warm accents — a vibrant, creative palette with high energy and expressive contrast.",
    kind: "preset",
    author: "Solidiom",
  },
  modes: {
    light: {
      surface: "#FAFAFE",
      "surface-raised": "#FFFFFF",
      "surface-overlay": "#FFFFFF",
      "surface-sunken": "#F3F0FF",
      foreground: "#1E1B4B",
      "foreground-muted": "#4C1D95",
      "foreground-subtle": "#7C3AED",
      "foreground-inverse": "#FAFAFE",
      border: "#C4B5FD",
      "border-muted": "#DDD6FE",
      "border-active": "#7C3AED",
      primary: "#7C3AED",
      "primary-hover": "#6D28D9",
      "primary-foreground": "#FFFFFF",
      secondary: "#8B5CF6",
      success: "#059669",
      warning: "#D97706",
      destructive: "#DC2626",
      "focus-ring": { ref: "primary" },
      "focus-ring-width": "2px",
      "radius-sm": "8px",
      radius: "12px",
      "radius-lg": "16px",
      "radius-full": "999px",
      "shadow-sm": "0 1px 2px 0 rgba(30, 27, 75, 0.04)",
      "shadow-md": "0 2px 6px -1px rgba(30, 27, 75, 0.06), 0 1px 4px -2px rgba(30, 27, 75, 0.04)",
      "shadow-lg": "0 8px 24px -4px rgba(30, 27, 75, 0.08), 0 2px 8px -4px rgba(30, 27, 75, 0.04)",
      "font-size-xs": "0.75rem",
      "line-height-xs": "1rem",
      "font-size-sm": "0.875rem",
      "line-height-sm": "1.25rem",
      "font-size-base": "0.875rem",
      "line-height-base": "1.25rem",
      "font-size-md": "1.125rem",
      "line-height-md": "1.5rem",
      "font-size-lg": "1.25rem",
      "line-height-lg": "1.5rem",
      "font-size-xl": "1.875rem",
      "line-height-xl": "2.25rem",
    },
    dark: {
      surface: "#1A1033",
      "surface-raised": "#2D1B69",
      "surface-overlay": "#2D1B69",
      "surface-sunken": "#0D0A1F",
      foreground: "#EDE9FE",
      "foreground-muted": "#A78BFA",
      "foreground-subtle": "#7C3AED",
      "foreground-inverse": "#1A1033",
      border: "#4C1D95",
      "border-muted": "#2D1B69",
      "border-active": "#C084FC",
      primary: "#C084FC",
      "primary-hover": "#D8B4FE",
      "primary-foreground": "#1A1033",
      secondary: "#A855F7",
      success: "#34D399",
      warning: "#FBBF24",
      destructive: "#F87171",
      "focus-ring": { ref: "primary" },
      "focus-ring-width": "2px",
      "radius-sm": "8px",
      radius: "12px",
      "radius-lg": "16px",
      "radius-full": "999px",
      "shadow-sm": "0 1px 3px 0 rgba(0, 0, 0, 0.2)",
      "shadow-md": "0 3px 8px -1px rgba(0, 0, 0, 0.3), 0 1px 4px -2px rgba(0, 0, 0, 0.2)",
      "shadow-lg": "0 10px 30px -4px rgba(0, 0, 0, 0.4), 0 4px 10px -4px rgba(0, 0, 0, 0.25)",
      "font-size-xs": "0.75rem",
      "line-height-xs": "1rem",
      "font-size-sm": "0.875rem",
      "line-height-sm": "1.25rem",
      "font-size-base": "0.875rem",
      "line-height-base": "1.25rem",
      "font-size-md": "1.125rem",
      "line-height-md": "1.5rem",
      "font-size-lg": "1.25rem",
      "line-height-lg": "1.5rem",
      "font-size-xl": "1.875rem",
      "line-height-xl": "2.25rem",
    },
  },
}

export const REFERENCE_THEMES: Readonly<Record<string, ThemeDefinition>> = {
  "solidiom-default": SOLIDIOM_DEFAULT_THEME,
  ocean: OCEAN_THEME,
  forest: FOREST_THEME,
  slate: SLATE_THEME,
  aurora: AURORA_THEME,
}
