/**
 * GENERATED by tools/recipe-emit-unocss.ts from tools/recipe-contract-definitions.ts ("badge")
 * Do not edit by hand — edit the definition and re-run the emitter.
 */

import { cva, type VariantProps } from "class-variance-authority"

export const badgeVariants = cva("solidiom-badge", {
  variants: {
    variant: {
      default: "solidiom-badge--default",
      secondary: "solidiom-badge--secondary",
      destructive: "solidiom-badge--destructive",
      outline: "solidiom-badge--outline",
    },
  },
  defaultVariants: {
    variant: "default",
  },
})

export type BadgeVariantProps = VariantProps<typeof badgeVariants>
